### ISSUE TITLE
Missing model.destroy

### ISSUE THREAD

**Issue by Hypercubed** [chiasm-project/chiasm-layout#7]
We seam to have lost the model.destroy API.  We need a way to remove the resize listener.

**Comment by Hypercubed** [comment]
https://github.com/chiasm-project/chiasm/commit/dc4997be0f3b62df40798e8f7d39ef8bcae1ca16

**Comment by curran** [comment]
Thanks for pointing this out. Just fixed. All the best!

**Comment by Hypercubed** [comment]
Great, thanks!  Maybe publish to npm when you have time.

On a separate note, would you consider a few PRs for chiasm modules to bump lodash?

(I'm pushing myself to release a v1.0.0 or Project-X, cleaning up some dependencies now).

**Comment by curran** [comment]
Done - now at v0.3.0.

Sure, I'll gladly accept PRs to bump lodash.

(Very cool! Congrats on making it to 1.0)

**Comment by Hypercubed** [comment]
Hi Curran,

Can you please publish to npm?

**Comment by curran** [comment]
Done. Sorry, thought I did that before, but there were errors that stopped the publish step.

**Comment by Hypercubed** [comment]
NP.  Thanks!
